version: "3"
services:
  postgres.boacausa.local:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
