default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: boacausa_development

test:
  <<: *default
  database: boacausa_test

production:
  <<: *default
  database: boacausa_production
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>